<script setup>
import { computed, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { trackEvent } from '../utils/analytics'
const route=useRoute(), whatsappNumber='6285360061021', step=ref(1), submitted=ref(false)
const form=reactive({name:'',business:'',industry:String(route.query.industry||''),service:String(route.query.service||route.query.layanan||''),budget:'Belum menentukan budget',timeline:'Belum menentukan timeline',contact:'',needs:''})
const context=computed(()=>({demo:String(route.query.demo||''),package:String(route.query.package||route.query.paket||''),source:String(route.query.source||''),industry:String(route.query.industry||'')}))
const serviceLabels={'':'Belum yakin — bantu rekomendasikan','mulai-digital':'Mulai Digital','landing-page':'Landing Page','company-profile':'Company Profile','toko-online':'Toko Online','sistem-bisnis':'Sistem Bisnis','custom-development':'Custom Development','managed-website':'Managed Website'}
const serviceChoices=[['','Belum Yakin'],['company-profile','Website Company Profile'],['landing-page','Landing Page'],['toko-online','Toko Online'],['sistem-bisnis','Sistem Bisnis'],['custom-development','Aplikasi Khusus']]
const summary=computed(()=>[['Kebutuhan',serviceLabels[form.service]],['Bisnis',form.business||'—'],['Budget',form.budget],['Timeline',form.timeline],...(context.value.demo?[['Referensi demo',context.value.demo]]:[]),...(context.value.package?[['Paket',context.value.package]]:[])])
const message=computed(()=>['Halo InfitechDigi, saya ingin konsultasi kebutuhan digital.','',`Nama: ${form.name||'-'}`,`Bisnis: ${form.business||'-'}`,`Jenis bisnis: ${form.industry||'-'}`,`Kebutuhan: ${serviceLabels[form.service]}`,`Perkiraan budget: ${form.budget}`,`Target waktu: ${form.timeline}`,...(context.value.demo?[`Referensi demo: ${context.value.demo}`]:[]),...(context.value.package?[`Paket yang dilihat: ${context.value.package}`]:[]),`Kontak: ${form.contact||'-'}`,'','Kebutuhan / tujuan:',form.needs||'-',...(context.value.source?['',`Sumber: ${context.value.source}`]:[])].join('\n'))
function chooseService(v){form.service=v;trackEvent('start_consultation',{service:v||'unsure',source:context.value.source,demo:context.value.demo})}
function next(){if(step.value<4)step.value++} function back(){if(step.value>1)step.value--}
function submit(){submitted.value=true;trackEvent('submit_lead',{service:form.service||'unsure',demo:context.value.demo,industry:form.industry,budget:form.budget,source:context.value.source,package:context.value.package});trackEvent('click_whatsapp',{source:'contact',service:form.service||'unsure',demo:context.value.demo});window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message.value)}`,'_blank','noopener,noreferrer')}
</script>
<template>
<section class="page-hero"><div class="container narrow"><span class="eyebrow">Konsultasi Awal Gratis</span><h1>Ceritakan kebutuhan bisnis Anda.</h1><p>Tidak perlu menentukan teknologi sendiri. Jawab beberapa hal penting, cek ringkasannya, lalu lanjutkan melalui WhatsApp resmi InfitechDigi.</p></div></section>
<section class="section"><div class="container contact-grid">
<div><span class="eyebrow">Project Brief</span><h2>Konteks yang cukup, tanpa form yang melelahkan.</h2><p>Perkiraan budget membantu menentukan scope dan bukan komitmen pembayaran.</p><div v-if="context.demo" class="contact-note"><strong>Referensi Demo</strong><p>Concept <b>{{context.demo}}</b> otomatis ikut dalam konsultasi.</p></div><div class="contact-summary"><span class="eyebrow">Ringkasan Project</span><div v-for="item in summary" :key="item[0]"><span>{{item[0]}}</span><strong>{{item[1]}}</strong></div></div></div>
<form class="contact-form" @submit.prevent="submit">
<div class="contact-steps" aria-label="Progress form"><i v-for="n in 4" :key="n" class="contact-step-dot" :class="{active:n<=step}"></i></div><div class="contact-step-head"><strong>Langkah {{step}} dari 4</strong><small>{{['Pilih kebutuhan','Tentang project','Kontak & tujuan','Konfirmasi'][step-1]}}</small></div>
<template v-if="step===1"><div class="choice-grid"><button v-for="c in serviceChoices" :key="c[1]" type="button" class="choice-card" :class="{active:form.service===c[0]}" @click="chooseService(c[0])">{{c[1]}}</button></div><div class="contact-step-actions"><span></span><button type="button" class="btn" @click="next">Lanjut →</button></div></template>
<template v-else-if="step===2"><label>Nama bisnis<input v-model="form.business" autocomplete="organization" placeholder="Nama bisnis / organisasi"></label><label>Jenis bisnis<input v-model="form.industry" placeholder="Travel, konstruksi, retail, dll."></label><label>Perkiraan budget<select v-model="form.budget"><option>Belum menentukan budget</option><option>Di bawah Rp2 juta</option><option>Rp2–5 juta</option><option>Rp5–10 juta</option><option>Rp10–20 juta</option><option>Rp20–50 juta</option><option>Di atas Rp50 juta</option></select></label><label>Target waktu<select v-model="form.timeline"><option>Belum menentukan timeline</option><option>Secepatnya</option><option>1–2 bulan</option><option>2–3 bulan</option><option>3 bulan atau lebih</option></select></label><div class="contact-step-actions"><button type="button" class="btn btn-secondary" @click="back">← Kembali</button><button type="button" class="btn" @click="next">Lanjut →</button></div></template>
<template v-else-if="step===3"><label>Nama<input v-model="form.name" required autocomplete="name" placeholder="Nama Anda"></label><label>Nomor WhatsApp / email<input v-model="form.contact" required placeholder="Kontak yang mudah dihubungi"></label><label>Ceritakan kebutuhan<textarea v-model="form.needs" required rows="5" :placeholder="context.demo?`Saya tertarik dengan konsep ${context.demo} dan ingin...`:'Kondisi bisnis saat ini, tujuan, atau fitur yang dibutuhkan'"></textarea></label><div class="contact-step-actions"><button type="button" class="btn btn-secondary" @click="back">← Kembali</button><button type="button" class="btn" :disabled="!form.name||!form.contact||!form.needs" @click="next">Review →</button></div></template>
<template v-else><div class="contact-summary"><div v-for="item in summary" :key="item[0]"><span>{{item[0]}}</span><strong>{{item[1]}}</strong></div></div><p class="form-privacy">Data digunakan untuk menyusun pesan konsultasi dan tidak dikirim ke server dari halaman ini.</p><div class="contact-step-actions"><button type="button" class="btn btn-secondary" @click="back">← Edit</button><button class="btn" type="submit">Lanjutkan ke WhatsApp →</button></div><p v-if="submitted" class="success">Pesan sudah disiapkan. Jika WhatsApp tidak terbuka, izinkan pop-up untuk halaman ini.</p></template>
</form></div></section>
</template>
