<script setup>
import { computed, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { services } from '../data/site'
import { getPublicDemos, getDemoRoute } from '../data/demos'
const route = useRoute()
const router = useRouter()
const selected=ref('mulai-digital')
const solutions=[
{id:'mulai-digital',n:'01',need:'Saya baru ingin mulai go digital',title:'Bangun fondasi digital yang rapi',intro:'Cocok untuk bisnis lokal yang ingin mulai lebih mudah ditemukan, dihubungi, dan mencatat pelanggan tanpa langsung membangun sistem besar.',symptoms:['Informasi bisnis belum tertata secara digital','Pelanggan masih mengandalkan chat manual','Belum punya database pelanggan yang rapi'],outcome:'Mulai Digital membantu menyiapkan fondasi praktis seperti komunikasi pelanggan, Google Business Profile, database pelanggan, dan form digital.'},
{id:'company-profile',n:'02',need:'Bisnis saya perlu terlihat lebih profesional',title:'Bangun kredibilitas dengan website resmi',intro:'Untuk bisnis yang sudah berjalan tetapi membutuhkan pusat informasi resmi agar calon pelanggan lebih yakin sebelum menghubungi.',symptoms:['Informasi bisnis tersebar di WhatsApp atau media sosial','Calon pelanggan sulit memahami layanan dan pengalaman Anda','Belum ada profil resmi yang mudah dibagikan'],outcome:'Company Profile menyatukan profil, layanan, pengalaman, proyek, dan kontak dalam website profesional yang mewakili bisnis Anda.',demo:'company-profile'},
{id:'landing-page',n:'03',need:'Saya ingin mendapatkan lebih banyak calon pelanggan',title:'Fokuskan campaign ke satu tujuan',intro:'Untuk promosi, iklan, event, produk, atau jasa yang membutuhkan halaman khusus dengan pesan dan CTA yang jelas.',symptoms:['Traffic iklan langsung diarahkan ke WhatsApp tanpa penjelasan','Promosi bercampur dengan informasi lain','Sulit mengukur respons dari campaign tertentu'],outcome:'Landing Page membantu mengarahkan perhatian calon pelanggan pada satu penawaran dan satu tindakan utama.',demo:'landing-page'},
{id:'toko-online',n:'04',need:'Saya ingin mulai jualan online',title:'Buat katalog dan alur order milik sendiri',intro:'Untuk bisnis yang ingin produk lebih mudah ditemukan, dipilih, dan dipesan tanpa hanya mengandalkan katalog di chat atau media sosial.',symptoms:['Katalog produk sulit dibagikan dan diperbarui','Pelanggan harus bertanya satu per satu lewat chat','Produk belum punya etalase digital yang terstruktur'],outcome:'Toko Online dapat dimulai dari katalog + order WhatsApp, lalu berkembang ke cart, checkout, dan payment gateway sesuai kebutuhan.',demo:'toko-online'},
{id:'sistem-bisnis',n:'05',need:'Operasional bisnis mulai sulit dikelola manual',title:'Rapikan proses, data, dan workflow internal',intro:'Untuk bisnis yang mulai kewalahan dengan pencatatan terpisah, pekerjaan berulang, atau informasi operasional yang sulit dipantau.',symptoms:['Data tersebar di banyak file dan chat','Pekerjaan berulang masih dilakukan manual','Laporan membutuhkan waktu lama untuk disiapkan'],outcome:'Sistem Bisnis dirancang mengikuti proses kerja Anda untuk merapikan data, stok, pelanggan, laporan, dan workflow internal.'},
{id:'custom-development',n:'06',need:'Saya membutuhkan aplikasi dengan kebutuhan khusus',title:'Bangun aplikasi mengikuti proses bisnis Anda',intro:'Untuk kebutuhan yang tidak cocok dengan produk siap pakai dan membutuhkan web app, mobile app, portal, API, atau integrasi khusus.',symptoms:['Workflow bisnis terlalu spesifik untuk software umum','Perlu integrasi antar sistem atau API','Ada ide produk digital yang perlu dibangun dari awal'],outcome:'Custom Development dimulai dari discovery agar scope, arsitektur, fitur, dan estimasi dibangun berdasarkan kebutuhan nyata.'}
]
const current=computed(()=>solutions.find(x=>x.id===selected.value)||solutions[0])
const service=computed(()=>services.find(x=>x.slug===current.value.id))
const demos=computed(()=>current.value.demo?getPublicDemos().filter(x=>x.service===current.value.demo).sort((a,b)=>(b.priority||0)-(a.priority||0)).slice(0,3):[])
const validNeeds = computed(() => new Set(solutions.map(x => x.id)))
const applyNeedFromRoute = (need, shouldScroll = false) => {
  const id = typeof need === 'string' && validNeeds.value.has(need) ? need : 'mulai-digital'
  selected.value = id
  if (shouldScroll && typeof need === 'string' && validNeeds.value.has(need)) {
    requestAnimationFrame(() => document.querySelector('#arah-solusi')?.scrollIntoView({ behavior:'smooth', block:'start' }))
  }
}
watch(() => route.query.need, (need, oldNeed) => {
  applyNeedFromRoute(need, oldNeed !== undefined || typeof need === 'string')
}, { immediate:true })
const choose = async (id) => {
  if (!validNeeds.value.has(id)) return
  selected.value = id
  await router.replace({ path:'/solusi', query:{ ...route.query, need:id } })
  requestAnimationFrame(() => document.querySelector('#arah-solusi')?.scrollIntoView({ behavior:'smooth', block:'start' }))
}
</script>
<template>
<section class="solution-hero"><div class="container solution-hero-grid"><div><span class="eyebrow">Temukan Solusi</span><h1>Apa yang ingin Anda <span>tingkatkan</span> dari bisnis Anda?</h1><p>Anda tidak harus tahu nama layanan yang dibutuhkan. Mulai dari kondisi bisnis Anda, lalu lihat arah solusi digital yang paling relevan.</p><div class="hero-actions"><a class="btn btn-primary" href="#pilih-kebutuhan">Temukan Solusi ↓</a><router-link class="btn btn-secondary" to="/kontak?source=solution-discovery">Konsultasi Gratis</router-link></div></div><div class="solution-map"><small>ALUR MENEMUKAN SOLUSI</small><strong>Kebutuhan Bisnis</strong><div class="solution-map-list"><span>Mulai Digital</span><span>Lebih Profesional</span><span>Tambah Leads</span><span>Jualan Online</span><span>Rapikan Operasional</span><span>Aplikasi Khusus</span></div><b>Kebutuhan → Solusi → Demo → Konsultasi</b></div></div></section>
<section id="pilih-kebutuhan" class="section"><div class="container"><div class="solution-heading"><div><span class="eyebrow">Mulai dari kondisi Anda</span><h2>Pilih yang paling dekat dengan bisnis Anda.</h2></div><p>Tidak perlu memilih berdasarkan teknologi. Pilih berdasarkan hal yang ingin Anda perbaiki atau capai.</p></div><div class="solution-choice-grid"><button v-for="x in solutions" :key="x.id" class="solution-choice" :class="{active:selected===x.id}" @click="choose(x.id)"><span>{{x.n}}</span><strong>{{x.need}}</strong><b>→</b></button></div></div></section>
<section id="arah-solusi" class="section section-soft solution-recommendation"><div class="container"><div class="recommendation-top"><div><span class="eyebrow">Arah Solusi</span><p class="recommendation-need">“{{current.need}}”</p><h2>{{current.title}}</h2><p class="recommendation-intro">{{current.intro}}</p></div><aside class="recommendation-card"><small>SOLUSI YANG RELEVAN</small><h3>{{service?.title}}</h3><p>{{service?.desc}}</p><strong>{{service?.price}}</strong><router-link class="btn btn-primary" :to="`/layanan/${current.id}`">Pelajari {{service?.title}} →</router-link></aside></div><div class="recommendation-details"><article><strong>Yang biasanya terjadi</strong><ul><li v-for="s in current.symptoms" :key="s">{{s}}</li></ul></article><article><strong>Bagaimana kami membantu</strong><p>{{current.outcome}}</p><router-link :to="`/kontak?source=solution-discovery&service=${current.id}`" class="text-link">Diskusikan kebutuhan ini →</router-link></article></div>
<div v-if="demos.length" class="solution-demo-block"><div class="solution-demo-heading"><div><span class="eyebrow">Lihat arahnya</span><h2>Contoh tampilan yang relevan.</h2></div><router-link to="/demo" class="text-link">Jelajahi semua demo →</router-link></div><div class="solution-demo-grid"><router-link v-for="d in demos" :key="d.slug" :to="getDemoRoute(d)" class="solution-demo-card"><div class="solution-demo-image"><img v-if="d.coverImage" :src="d.coverImage" :alt="`Preview ${d.title}`" loading="lazy"><span>Demo / Concept</span></div><div><small>{{service?.title}}</small><h3>{{d.title}}</h3><p>{{d.description}}</p><b>Lihat Detail →</b></div></router-link></div></div></div></section>
<section class="section"><div class="container"><div class="solution-heading"><div><span class="eyebrow">Bertumbuh bertahap</span><h2>Solusi digital dapat berkembang bersama bisnis.</h2></div><p>Tidak semua kebutuhan harus dikerjakan sekaligus. Mulai dari fondasi yang paling relevan, lalu berkembang ketika bisnis membutuhkannya.</p></div><div class="solution-journey"><article><span>01</span><small>Mulai</small><h3>Fondasi Digital</h3><p>Rapikan kehadiran, komunikasi, dan data pelanggan dasar.</p></article><article><span>02</span><small>Tumbuhkan</small><h3>Website & Penjualan</h3><p>Bangun kredibilitas, campaign, dan kanal penjualan digital.</p></article><article><span>03</span><small>Rapikan</small><h3>Operasional</h3><p>Kurangi pekerjaan manual dan satukan proses bisnis penting.</p></article><article><span>04</span><small>Kembangkan</small><h3>Solusi Custom</h3><p>Bangun aplikasi dan integrasi khusus saat kebutuhan makin kompleks.</p></article></div></div></section>
<section class="solution-unsure"><div class="container"><div><span class="eyebrow eyebrow-light">Belum Yakin?</span><h2>Tidak perlu menentukan layanan sendiri.</h2><p>Ceritakan kondisi bisnis dan apa yang ingin Anda tingkatkan. Kami bantu memetakan pendekatan yang sesuai sebelum masuk ke scope dan biaya.</p></div><router-link class="btn btn-light" to="/kontak?source=solution-discovery&service=belum-yakin">Konsultasikan Kebutuhan →</router-link></div></section>
</template>
